#!/bin/sh
# Starts and stops [bcvpsd]
#

. /etc/rc.d/init.d/functions
#	/root/scripts/bcvpsd/bcvpsd.pl

#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.
# 
# chkconfig:   - 85 15
# description:  Redis is a persistent key-value database
# processname: redis_6379

EXEC=/root/scripts/bcvpsd/bcvpsd.pl
PID=`pidof [bcvpsd]`

case "$1" in
    start)
	if ( ! pidof [bcvpsd]  >> /dev/null ); then
                echo "Starting [bcvpsd] server..."
                $EXEC
	else
		 echo "[bcvpsd] is already running!"
	fi
        ;;
    stop)
	if ( pidof [bcvpsd]  >> /dev/null ); then
                echo "Stopping ..."
                kill -9 $PID
                echo "[bcvpsd] stopped"
	else
		echo "[bcvpsd] is not running!"
	fi
        ;;
    restart)
	if ( pidof [bcvpsd] >> /dev/null ); then
                echo "Stopping ..."
                kill -9 $PID
                echo "[bcvpsd] stopped"
		 echo "Starting [bcvpsd] server..."
                $EXEC
	else
		echo "Starting [bcvpsd] server..."
                $EXEC
	fi
	;;
    status)
	if ( pidof [bcvpsd]  >> /dev/null ); then
		echo '[bcvpsd] is running!'
	else
		echo '[bcvpsd] is not running!'
	fi
        ;;

    *)
        echo "Please use start, stop or restart as first argument"
        ;;
esac
exit $?
