#!/bin/bash
. /etc/init.d/functions

base_dir='/root/scripts/'
shortname="odtmon"
now=`date "+%d-%h-%Y %H:%M %Z"`
logdir="$base_dir/logs"
log="$logdir/$shortname.log"

user="ADDUSERHERE"

#path to monitor
path="/home/$user/public_html/wp-content/uploads/resumes/resume_files/"


BEEP="\x07"
ESC="\x1b["
RED=$ESC"31;01m"
GREEN=$ESC"32;01m"
YELLOW=$ESC"33;01m"
DBLUE=$ESC"34;01m"
MAGENTA=$ESC"35;01m"
BLUE=$ESC"36;01m"
WHITE=$ESC"37;01m"
GREY=$ESC"30;01m"
RESET=$ESC"39;49;00m"

programname=$0

function usage {
    echo "usage: $programname [-dfh]"
    echo "  -d      run as daemon in background"
    echo "  -f      run force convert of all .doc & .docx to .odt"
    echo "  -h      display help"
    exit 1
}

if [ ${#@} == 0 ]; then
	usage
fi

if [ $# -ne 1 ]; then
	usage
fi

if [ $1 == '-h' ]; then
	usage
fi


function log_me {
	echo -e "$GREEN[$WHITE+$GREEN]$DBLUE INFO:$BLUE $@$RESET"
	echo -e "[$now] INFO: $@" >> $log
}

function fatal_error {
	echo -e "$RED[$WHITE!$RED]$WIHTE FATAL ERROR:$RED $@$RESET$BEEP"
	echo -e "[$now] FATAL ERROR: $@" >> $log
	exit 1;
}

function STDERR () {
	cat - 1>&2
}

log_me "Checking for logging folder"
if [ ! -d $logdir ]; then
	mkdir -p $logdir
fi



function forceconvert {
	log_me "Force mode ON, scanning and converting all *.doc and *.docs from $path"
	#force
	for files in $(find $path -name '*.doc*' | grep -Ei '\.doc$|\.docx$'); do
                doc=$(echo -e $files | grep -Ei '\.doc$|\.docx$')
                if  [[  -n $doc ]]; then
                        file=$(basename -z $doc)
                        folder=$(dirname -z $doc)
                        log_me "Converting $folder/$file to .odt format"
                        if [ -f $doc ]; then
                                log_me "FILE: $file FOLDER: $folder\n"
                                /usr/bin/libreoffice --headless --convert-to odt $folder/$file --outdir $folder  > /dev/null 2>&1
                        fi
                fi	
	done
}
function fdaemonitor {
	log_me "Monitor mode: ON (running in background as daemon)"
	#mon
	inotifywait --quiet --recursive --monitor --event  close_write  --format "%w%f" $path | 
	while read files; do
		doc=$(echo -e $files | grep -Ei '\.doc$|\.docx$')
		if  [[  -n $doc ]]; then
			file=$(basename -z $doc)
			folder=$(dirname -z $doc)
			log_me "Converting $folder/$file to .odt format"
			if [ -f $doc ]; then 
				log_me "FILE: $file FOLDER: $folder\n"
				/usr/bin/libreoffice --headless --convert-to odt $folder/$file --outdir $folder  > /dev/null 2>&1
			fi
		fi
	done
}

if [ $1 == '-d' ]; then
	fdaemonitor
fi

if [ $1 == '-f' ]; then
	forceconvert
fi
