#!/bin/bash
pkill -9 httpd
sleep 1
for i in $(ipcs -s | grep nobody | awk '{print $2}'); do ipcrm sem $i; done
killall -9 /usr/bin/php
pidof /usr/local/varnish/sbin/varnishd | xargs kill -9
/etc/init.d/nginx restart
/etc/init.d/varnish restart
/usr/local/apache/bin/httpd -DSSL
killall -9 /usr/bin/php
rm -rf /var/cache/mod_pagespeed/*
